CREATE TABLE IF NOT EXISTS public.empresas (
    id_empresa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_legal text NOT NULL,
    nombre_comercial text,
    nit text,
    nrc text,
    giro_comercial text,
    direccion text,
    telefono text,
    email text,
    logo text,
    moneda text NOT NULL DEFAULT 'USD',
    pais text NOT NULL DEFAULT 'El Salvador',
    estado text NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.empresas (id_empresa, nombre_legal)
VALUES (1, 'Empresa principal')
ON CONFLICT (id_empresa) DO NOTHING;

ALTER TABLE public.libros_diarios
    ADD COLUMN IF NOT EXISTS id_empresa bigint,
    ADD COLUMN IF NOT EXISTS descripcion text,
    ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'ACTIVO',
    ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

UPDATE public.libros_diarios SET id_empresa = 1 WHERE id_empresa IS NULL;
ALTER TABLE public.libros_diarios ALTER COLUMN id_empresa SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_libros_diarios_empresa'
    ) THEN
        ALTER TABLE public.libros_diarios
            ADD CONSTRAINT fk_libros_diarios_empresa
            FOREIGN KEY (id_empresa) REFERENCES public.empresas(id_empresa);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_libros_diarios_empresa_nombre'
    ) THEN
        ALTER TABLE public.libros_diarios
            ADD CONSTRAINT uq_libros_diarios_empresa_nombre
            UNIQUE (id_empresa, nombre_libro);
    END IF;
END $$;

DROP VIEW IF EXISTS public.vw_historial_asientos;

CREATE VIEW public.vw_historial_asientos AS
SELECT
    l.id_libro,
    a.id_asiento,
    a.fecha,
    a.descripcion,
    s.codigo_cuenta,
    d.codigo_subcuenta,
    c.nombre_cuenta AS cuenta_principal,
    d.debe,
    d.haber
FROM public.detalles_asiento d
JOIN public.asientos a ON a.id_asiento = d.id_asiento
JOIN public.libros_diarios l ON l.id_libro = a.id_libro
JOIN public.subcuentas s ON s.codigo_subcuenta = d.codigo_subcuenta
JOIN public.cuentas_principales c ON c.codigo_cuenta = s.codigo_cuenta;
