CREATE TABLE public.kardex (
    id_movimiento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_articulo text NOT NULL DEFAULT 'UNICO',
    fecha date NOT NULL DEFAULT CURRENT_DATE,
    concepto text NOT NULL,
    tipo_movimiento text NOT NULL CHECK (tipo_movimiento IN ('INVENTARIO_INICIAL', 'COMPRA', 'VENTA', 'DEV_COMPRA', 'DEV_VENTA')),
    cantidad numeric NOT NULL,
    costo_unitario numeric NOT NULL,
    costo_total numeric NOT NULL,
    saldo_cantidad numeric NOT NULL,
    saldo_costo_unitario numeric NOT NULL,
    saldo_total numeric NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);