create table if not exists public.cuentas_principales (
    codigo_cuenta text primary key,
    nombre_cuenta text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.subcuentas (
    codigo_subcuenta text primary key,
    codigo_cuenta text not null references public.cuentas_principales(codigo_cuenta),
    nombre_subcuenta text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.libros_diarios (
    id_libro bigint generated by default as identity primary key,
    nombre_libro text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.asientos (
    id_asiento bigint generated by default as identity primary key,
    id_libro bigint not null references public.libros_diarios(id_libro),
    fecha date not null,
    descripcion text not null check (char_length(trim(descripcion)) between 1 and 500),
    created_at timestamptz not null default now()
);

create table if not exists public.detalles_asiento (
    id_detalle bigint generated by default as identity primary key,
    id_asiento bigint not null references public.asientos(id_asiento) on delete cascade,
    codigo_subcuenta text not null references public.subcuentas(codigo_subcuenta),
    debe numeric(14, 2) not null default 0 check (debe >= 0),
    haber numeric(14, 2) not null default 0 check (haber >= 0),
    check ((debe > 0 and haber = 0) or (debe = 0 and haber > 0))
);

create index if not exists idx_asientos_libro_fecha
    on public.asientos (id_libro, fecha desc, id_asiento desc);

create index if not exists idx_detalles_asiento_asiento
    on public.detalles_asiento (id_asiento, codigo_subcuenta);

alter table public.cuentas_principales enable row level security;
alter table public.subcuentas enable row level security;
alter table public.libros_diarios enable row level security;
alter table public.asientos enable row level security;
alter table public.detalles_asiento enable row level security;

create or replace view public.vw_historial_asientos as
select
    l.id_libro,
    a.id_asiento,
    a.fecha,
    a.descripcion,
    d.codigo_subcuenta,
    c.nombre_cuenta as cuenta_principal,
    d.debe,
    d.haber
from public.detalles_asiento d
join public.asientos a on a.id_asiento = d.id_asiento
join public.libros_diarios l on l.id_libro = a.id_libro
join public.subcuentas s on s.codigo_subcuenta = d.codigo_subcuenta
join public.cuentas_principales c on c.codigo_cuenta = s.codigo_cuenta;

create or replace function public.guardar_asiento_completo(
    p_id_libro bigint,
    p_fecha date,
    p_descripcion text,
    p_detalles jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id_asiento bigint;
    v_total_debe numeric(14, 2);
    v_total_haber numeric(14, 2);
begin
    if not exists (
        select 1 from public.libros_diarios where id_libro = p_id_libro
    ) then
        raise exception 'El libro diario no existe';
    end if;

    if jsonb_typeof(p_detalles) <> 'array' or jsonb_array_length(p_detalles) < 2 then
        raise exception 'El asiento debe contener al menos dos detalles';
    end if;

    if exists (
        select 1
        from jsonb_to_recordset(p_detalles) as d(codigo text, debe numeric, haber numeric)
        where d.codigo is null
           or trim(d.codigo) = ''
           or d.debe is null
           or d.haber is null
           or d.debe < 0
           or d.haber < 0
           or (d.debe = 0 and d.haber = 0)
           or (d.debe > 0 and d.haber > 0)
    ) then
        raise exception 'Cada detalle debe tener exactamente un importe positivo';
    end if;

    if exists (
        select 1
        from jsonb_to_recordset(p_detalles) as d(codigo text, debe numeric, haber numeric)
        where not exists (
            select 1
            from public.subcuentas s
            where s.codigo_subcuenta = d.codigo
        )
    ) then
        raise exception 'El asiento contiene una subcuenta inexistente';
    end if;

    select coalesce(sum(d.debe), 0), coalesce(sum(d.haber), 0)
    into v_total_debe, v_total_haber
    from jsonb_to_recordset(p_detalles) as d(codigo text, debe numeric, haber numeric);

    if v_total_debe <> v_total_haber then
        raise exception 'El asiento debe estar balanceado';
    end if;

    insert into public.asientos (id_libro, fecha, descripcion)
    values (p_id_libro, p_fecha, p_descripcion)
    returning id_asiento into v_id_asiento;

    insert into public.detalles_asiento (id_asiento, codigo_subcuenta, debe, haber)
    select v_id_asiento, d.codigo, d.debe, d.haber
    from jsonb_to_recordset(p_detalles) as d(codigo text, debe numeric, haber numeric);

    return v_id_asiento;
end;
$$;

revoke execute on function public.guardar_asiento_completo(bigint, date, text, jsonb)
    from public, anon, authenticated;
grant execute on function public.guardar_asiento_completo(bigint, date, text, jsonb)
    to service_role;
